output: docs
clean: true
sdk: iphonesimulator
source_directory: RNAlertController/
author: 'Rayhan Nabi'
module: RNAlertController
copyright: 'Copyright © Rayhan Nabi 2019, published under [MIT License](https://github.com/rayhannabi/RNAlertController/blob/master/LICENSE)'
readme: README.md
podspec: RNAlertController.podspec
github_url: https://github.com/rayhannabi/RNAlertController
min_acl: public
hide_documentation_coverage: true
theme: apple
undocumented_text: ''