os: osx
language: objective-c
osx_image: xcode11
xcode_project: RNAlertController.xcodeproj
xcode_scheme: RNAlertController
xcode_sdk: iphonesimulator13.0
xcode_destination: platform=iOS Simulator,OS=13.0

git:
  depth: 1

branches:
  except:
    - /release*/
    - /feature*/
    - /hotfix*/

jobs:
  include:
    - stage: test
      script: ./scripts/test.sh
    - stage: build
      if: tag IS present
      script: ./scripts/build.sh
      deploy:
        provider: releases
        api_key: $GITHUB_RELEASE_PAT
        skip_cleanup: true
        file:
          - builds/RNAlertController.framework.zip
          - builds/RNAlertController.framework.zip.sha1
        on:
          repo: rayhannabi/RNAlertController
          tags: true
