os: osx
language: objective-c
osx_image: xcode10.3
xcode_project: RNAlertController.xcodeproj
xcode_scheme: RNAlertController
xcode_sdk: iphonesimulator12.4
xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone Xs

branches:
  except:
    - /release*/
    - /feature*/

jobs:
  include:
    - stage: test
      script: ./scripts/test.sh
    - stage: build
      if: tag IS present
      script: ./scripts/build.sh
      deploy:
        provider: releases
        api_key: $GITHUB_RELEASE_PAT
        file:
          - builds/RNAlertController.framework.zip
          - builds/RNAlertController.framework.zip.sha1
        on:
          repo: rayhannabi/RNAlertController
          tags: true
